name: Build for release

on:
  push:
    tags:
      - "v*.*.*"

env:
  BUILD_TYPE: Release

jobs:
  build:
    concurrency: ci-${{ github.ref }}
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3

    - name: Install Dependencies
      run: sudo apt install cmake gcc-arm-none-eabi libnewlib-arm-none-eabi libstdc++-arm-none-eabi-newlib

    - name: Setup Rust
      run: |
        rustup self update
        rustup update stable
        rustup target add thumbv6m-none-eabi
        cargo install flip-link
    
    - name: Rust Cache
      uses: Swatinem/rust-cache@v2
      with:
        prefix-key: v0-rust-release

    - name: Build
      run: cargo build --release
    
    - name: Install SDK
      uses: actions/checkout@v3
      with:
        repository: raspberrypi/pico-sdk
        path: pico-sdk
        submodules: true

    - name: Build elf2uf2
      working-directory: ${{github.workspace}}/pico-sdk/tools/elf2uf2
      run: |
        cmake -B build -DCMAKE_BUILD_TYPE=${{env.BUILD_TYPE}}
        cmake --build build --config ${{env.BUILD_TYPE}}
    
    - name: Package binary
      run: ${{github.workspace}}/pico-sdk/tools/elf2uf2/build/elf2uf2 ${{github.workspace}}/target/thumbv6m-none-eabi/release/macropad_firmware ${{github.workspace}}/macropad_firmware.uf2
    
    - name: Upload Firmware
      uses: actions/upload-artifact@v3
      with:
        name: Firmware
        path: ${{github.workspace}}/macropad_firmware.uf2

    - name: Add Firmware to Release
      uses: softprops/action-gh-release@v1
      if: startsWith(github.ref, 'refs/tags/')
      with:
        files: ${{github.workspace}}/macropad_firmware.uf2